### ISSUE TITLE
user role for opbeans to read/write directly to elasticsearch

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-integration-testing#1032]
Hey folks

in opbeans-python, we have some code that reads from and writes to elasticsearch, to demo the elasticsearch instrumentation. Unfortunately, that stopped working since `compose.py` defaults to enabling authentication. Would it be possible to add an `opbeans_user` (or similar) user/role that has read/write access to `opbeans-*` indexes, and expose the user/password as environment variables to the opbeans services?

**Comment by v1v** [comment]
I see some references for other users/roles in https://github.com/elastic/apm-integration-testing/pull/416

I don't know how the password is generated

**Comment by beniwohli** [comment]
@v1v yup, generating the password is the part that I don't understand, too
