### ISSUE TITLE
Cannot run 7.x build candidates with snapshot registry

### ISSUE THREAD

**Issue by axw** [elastic/apm-integration-testing#1068]
I'd like to test the 7.12 build candidates with Fleet, using the APM package in the snapshot package registry. When running a build candidate of Kibana, it will interact with the production package registry by default. This can be overridden with `XPACK_FLEET_REGISTRYURL` (`xpack.fleet.registryUrl`).

When running the managed APM Server service, one can pass the `--package-registry-snapshot` flag to direct it to use the snapshot registry. However, this only sets `XPACK_FLEET_REGISTRYURL` for the managed APM Server service. It should also be set for the Kibana process, so Kibana can fetch packages from the appropriate registry.

**Comment by kuisathaverat** [comment]
I think this setting is not implemented yet, IIRC the registry is forced based on the version you are using see https://github.com/elastic/kibana/pull/90327

**Comment by axw** [comment]
Yep, I'm in the process of adding a flag to control the registry URL used in Kibana.
