### ISSUE TITLE
Error when editing the APM integration configuration

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-integration-testing#1074]
Not sure if this is a bug in apm-integration-testing or apm-server, but figured I'd start here. FWIW, I'm able to edit the system integration settings without error.

## Summary

I'm unable to edit the `apm-integration-testing` Elastic APM integration after it's been set up. To reproduce, run:

```
./scripts/compose.py start master --with-elastic-agent --apm-server-managed --with-opbeans-java
```

Then, go to **Fleet** / **Policies** / **Default policy**. In the **Actions** hamburger menu for `apm-integration-testing`, select **Edit integration**. Finally, click the carrot to expand the **Collect application traces** settings.

<img width="1304" alt="Screen Shot 2021-03-02 at 11 09 25 AM" src="https://user-images.githubusercontent.com/5618806/109701379-c8ff4880-7b47-11eb-9122-d189c456644c.png">

**Comment by kuisathaverat** [comment]
it is resolved.
