### ISSUE TITLE
[CI] timeout for the ECK testing

### ISSUE THREAD

**Issue by v1v** [elastic/apm-integration-testing#1080]
![image](https://user-images.githubusercontent.com/2871786/110785663-1aec5080-8263-11eb-8217-a94ffe79722d.png)

See https://apm-ci.elastic.co/job/apm-it-eck/job/master/288/console

**Comment by kuisathaverat** [comment]
It seems related to the PHP agent
<img width="1911" alt="Screenshot 2021-03-11 at 13 23 07" src="https://user-images.githubusercontent.com/5400788/110786868-eed5cd00-826c-11eb-9569-2527a4e0c092.png">

**Comment by kuisathaverat** [comment]
that it is failing right now https://apm-ci.elastic.co/blue/organizations/jenkins/apm-it-eck/detail/master/289/tests

**Comment by kuisathaverat** [comment]
obsolete there is other issues now
