### ISSUE TITLE
Better Elastic Agent Integration ES Output URL

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#1178]
When starting an environment relying on agent: `compose.py --with-elastic-agent --apm-server-managed --all`, APM Server is unable to reach elasticsearch, reporting (in `/usr/share/elastic-agent/state/data/logs/default/apm-server-json.log`)

```
{"log.level":"info","@timestamp":"2021-06-16T19:00:22.429Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/output.go","file.line":145},"message":"Attempting to reconnect to backoff(elasticsearch(http://localhost:9200)) with 1163 reconnect attempt(s)","ecs.version":"1.6.0"}
````

Fleet is by configuring the elasticsearch output for integrations to `http://localhost:9200`.  Updating this to `http://elasticsearch:9200` resolves the issue, eg:

```
curl -XPUT -H "kbn-xsrf: 8.0.0" http://admin:changeme@localhost:5601/api/fleet/outputs/c3cdcef0-ce07-11eb-b921-210052e73eaa -H 'Content-Type: application/json' --data-raw '{"hosts":["http://elasticsearch:9200"],"config_yaml":""}'
```

For agents connecting to the fleet server running under apm-it's docker compose, `elasticsearch` can resolve to `localhost` via `/etc/hosts` or similiar mechanism.

**Comment by graphaelli** [comment]
for now, with a fresh apm-it:

```
curl -XPUT -H "kbn-xsrf: 8.0.0" http://admin:changeme@localhost:5601/api/fleet/outputs/$(curl -s http://admin:changeme@localhost:5601/api/fleet/outputs | jq -r .items[0].id) -H 'Content-Type: application/json' --data-raw '{"hosts":["http://elasticsearch:9200"],"config_yaml":""}'
```

**Comment by kuisathaverat** [comment]
this can be configured by adding `xpack.fleet.agents.elasticsearch.host: ${ESLASTICSEARCH_URL}` to the kibana configuration.

**Comment by graphaelli** [comment]
That has been set for awhile but was apparently broken, it seems to be fixed now.
