### ISSUE TITLE
Clarify readme on how to run Opbeans sample apps

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-integration-testing#124]
It is not clear which requirements are needed to run the Opbeans apps, the readme says you need `make env` and virtual env but in theory is not needed.

We should have really clear instructions on how to run only opbeans maybe even separate them given that most of the people will only be running these.

**Comment by graphaelli** [comment]
see https://github.com/elastic/apm-integration-testing/blob/master/QUICKSTART.md

closed by #179
