### ISSUE TITLE
--no-elasticsearch flag doesn't work

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-integration-testing#132]
Error: 
Service 'apm-server' depends on service 'elasticsearch' which is undefined.

**Comment by graphaelli** [comment]
Should this work or not be an option?

**Comment by jalvz** [comment]
would be nice if it works, but i guess that is somewhat complicated (or at least more complicated than not allowing it)

do you think is fine to not allow it?

not high prio any case

**Comment by graphaelli** [comment]
Agreed, would be nice if it works and shouldn't be a big effort, similar to our `disable_apm_server` checks in the agents.
