### ISSUE TITLE
APM server managed support on compose.py

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#1434]
Reviewing the `compose.py` support to run the APM server in managed mode I wonder if maintaining support for running the APM Server on managed mode for version 7.x is still something we want. My main concerns are:

* Configuration in 7.x is different than in 8.x
  * Access to Kibana and Elasticsearch is different (user+password vs API tokens)
  * The environment variables to configure settings are different
  * The default policies does not exist on Kibana 8+
* Standalone run mode is not deprecated

cc @elastic/observablt-robots @elastic/apm-server

**Comment by kuisathaverat** [comment]
https://github.com/elastic/apm-integration-testing/pull/1435

**Comment by axw** [comment]
Given that APM Server standalone (legacy) is still supported, I think it might be premature to remove support.

What prompted this? Is the maintenance actively causing pain?

**Comment by kuisathaverat** [comment]
>Given that APM Server standalone (legacy) is still supported, I think it might be premature to remove support.

nothing is removed, the thing is implementing only APM Server managed for 8.x. Standalone will work on both 7.x and 8.x if we apply the changes needed.

**Comment by axw** [comment]
Sorry, I misunderstood and thought you wanted to support only managed in 8.x, and no longer standalone.

> nothing is removed

https://github.com/elastic/apm-integration-testing/pull/1435 removes support for running the APM integration with 7.x doesn't it?

**Comment by simitt** [comment]
I don't think we should remove support for managed APM Server in `7.x`. When running the `7.17` stack, one needs to run it from the `7.x` branch. It is important that  we can test managed mode in `7.17` and also test upgrade scenarios.

**Comment by kuisathaverat** [comment]
In that case, I suggest implementing the support of 8+ in a new container instead of mixing 7.x and 8.x, if you agree I can make the changes on https://github.com/elastic/apm-integration-testing/issues/1440 to have 2 separate implementations on for 7.x and another for 8.x

**Comment by simitt** [comment]
I'm ok with having two separate implementations, especially given the fact that there are breaking changes in `8.1`, requiring a change in the setup anyways.
