### ISSUE TITLE
Fix setup with Elastic Agent and Fleet

### ISSUE THREAD

**Issue by simitt** [elastic/apm-integration-testing#1440]
Fleet removed default agent policies in `8.1`(https://github.com/elastic/kibana/pull/121628), and the Elastic Agent is currently adapting behavior to it (https://github.com/elastic/beats/pull/30256). These changes break the current setup logic for [managed apm-server](https://github.com/elastic/apm-integration-testing/blob/main/docker/apm-server/managed/main.go#L21). When updating to this new logic, instead of relying on a default policy with fleet-server integration being there by default, an agent policy with the fleet-server integration now needs to be created explicitly.

**Comment by kuisathaverat** [comment]
this change is implemented at https://github.com/elastic/apm-integration-testing/pull/1435 is waiting for a decision on https://github.com/elastic/apm-integration-testing/issues/1434

**Comment by kuisathaverat** [comment]
It is alredy implemented
