### ISSUE TITLE
--apm-server-managed has hard dependency on kibana service

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-integration-testing#1452]
Running APM IT with `--apm-server-managed` and `--no-kibana` leads to the following error:

```
➜  apm-integration-testing git:(main) ./scripts/compose.py start 8.2.0 --skip-download --no-kibana --apm-server-managed --with-elastic-agent --elastic-agent-kibana-url=http://0.0.0.0:5603/foo --apm-server-kibana-url=http://0.0.0.0:5603/foo
Starting/Building stack services..

no such service: kibana
```

I would expect to be able to use `--apm-server-managed` without starting the Kibana service, as I want to connect to my separately running Kibana instance.

**Comment by kuisathaverat** [comment]
`--apm-server-kibana-url=http://0.0.0.0:5603/foo` in managed mode is `--apm-managed-kibana-url=http://0.0.0.0:5603/foo`,  `--apm-server-managed ` is not needed.  

```
/scripts/compose.py start 8.2.0 --skip-download --no-kibana --with-elastic-agent --elastic-agent-kibana-url=http://0.0.0.0:5603/foo --apm-managed-kibana-url=http://0.0.0.0:5603/foo
```

The Elastic Agent and The APM server will use the Kibana instance passed as a parameter, but a Kibana instance is launched and stopped at the end of the start, this was the workaround we found to launch APM managed and configure it, and after that allow to run a custom Kibana instance.

https://github.com/elastic/apm-integration-testing/pull/1468
