### ISSUE TITLE
APM Server container exits when it cannot reach Kibana

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-integration-testing#1467]
When running APM Integration Testing with `--no-kibana`, the APM Server container exists because it cannot reach Kibana:

`Error: http POST request to http://kibana:5601/api/fleet/setup fails: fail to execute the HTTP POST request: Post "http://kibana:5601/api/fleet/setup": lookup kibana on 127.0.0.11:53: no such host. Response: `

I would like it to be possible to run APM Integration Testing with `--no-kibana` without having to try and figure out how to connect the APM Server container to my local Kibana instance (which is complicated, I've been told).

Script I'm running (after wiping all docker volumes):

`./scripts/compose.py start main --no-kibana`

**Comment by dgieselaar** [comment]
Some context: this is how we [recommend developers to start working with APM locally](https://www.elastic.co/guide/en/kibana/current/kibana-debugging.html#_running_kibana_with_the_apm_agent_locally). We also use it in the APM UI team if the test clusters are not available or if we want to index data locally. The fact that this doesn't work out is a big issue for us.

**Comment by simitt** [comment]
A quick investigation looks like https://github.com/elastic/apm-integration-testing/pull/1459/ broke this use case; cc @kuisathaverat 

Can we collect and summarize the most important commands somewhere? It is really hard to ensure no combinations of flags are broken while keeping everything up-to-date.

**Comment by kuisathaverat** [comment]
>Can we collect and summarize the most important commands somewhere? It is really hard to ensure no combinations of flags are broken while keeping everything up-to-date.

let's add the used flags, we do not have telemetry about the used flags, and we ask several times to know how users use the tool to know which flags are used without any success. Also since now is all configured through the APM integration some settings have changed.

@simitt  Is there a way to run APM standalone without Kibana? I mean, you need the APM integration but I dunno if there is a way to install it without Kibana. if it is not possible, it'd be complicated to run compose with `--no-kibana` flag

**Comment by dgieselaar** [comment]
One workaround is to run kibana from APM IT on a different port than your local Kibana instance:

`/scripts/compose.py start main --kibana-port=6601 --elastic-agent-kibana-url=http://localhost:6601`

However, I'm worried that this would quickly create conflicts as two slightly different kibana versions will end up writing to the same indices. If there is such a conflict I'm not sure how to workaround it, as both Kibana instances should be healthy for this setup to work.

**Comment by kuisathaverat** [comment]
As a workaround, you can start the deployment with Kibana, when everything is up and running then stop Kibana, from this point you can start your local Kibana instance.

```
./scripts/compose.py start main 
docker-compose stop kibana
```

**Comment by simitt** [comment]
> @simitt Is there a way to run APM standalone/managed without Kibana? I mean, you need the APM integration but I dunno if there is a way to install it without Kibana.

One can define the apm package in the Kibana configuration. As long as Kibana is running somewhere in the right version, and can connect to the same ES host, it will install apm assets on startup.
```
xpack.fleet.packages:
  - name: apm
    version: latest
```

**Comment by simitt** [comment]
For the development case, developers could add that to their kibana config. But yes, when running managed apm-server, one needs to install the integration, and without Kibana/Fleet this gets messy.

**Comment by dgieselaar** [comment]
I think regardless of whether the integration is installed the APM Server container still exists when it cannot connect to Kibana. Or did I misunderstand?

**Comment by kuisathaverat** [comment]
>For the development case, developers could add that to their kibana config. But yes, when running managed apm-server, one needs to install the integration, and without Kibana/Fleet this gets messy.

managed is the configuration most of the users would use.
