### ISSUE TITLE
ECK testing broken

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-integration-testing#1505]
The ECK tests are failing with errors like the following:
<img width="1307" alt="Screenshot 2022-07-29 at 12 06 49" src="https://user-images.githubusercontent.com/111616/181736637-86388a72-1410-427e-b9b4-0aa7e73cca83.png">

**Comment by kuisathaverat** [comment]
It looks flaky, it is waiting for Elastic search up and running

**Comment by cachedout** [comment]
@kuisathaverat I'm not sure it's flaky. It has been failing for over two months.

**Comment by kuisathaverat** [comment]
I see, I will take a look, it is weird.

**Comment by cachedout** [comment]
@kuisathaverat Looks like [other steps failed as well](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-it-eck/detail/main/155/pipeline). Could it be that the new auth plugin is required now?

**Comment by kuisathaverat** [comment]
the oath message is a warning, it is already patched in the observability test environments, after 1.25 you need to install a plugin to authenticate

**Comment by kuisathaverat** [comment]
I am checking ES does not start

**Comment by kuisathaverat** [comment]
This was resolved in the past by ECK, I dunno why it comes back

```
bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/elastic-stack.log
```
