### ISSUE TITLE
Opbeans: implement randomized distributed tracing

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-integration-testing#196]
To have somewhat realistic test data for the UI, the Opbeans services should implement distributed tracing amongst each other. The plan is as follows:

 * when using `compose.py`, an environment variable, `OPBEANS_SERVICES` will be set for all opbeans services, containing a list of all opbeans services in a comma-separated list, e.g. 
    
        OPBEANS_SERVICES=opbeans-node,opbeans-python,opbeans-go
    
   these services can either be:
     * "opbeans-xyz", in which case the base URL `http://opbeans-xyz:3000` should be used
     * or an URL that starts with `http`, in which case the URL should be used verbatim as base URL
       
* when a GET request to `/api/*` comes in, the opbeans service flips a coin. Depending on the outcome, it either serves the request itself, or forwards the request via instrumented HTTP-request to one of the services from `OPBEANS_SERVICES` using the URL `http://opbeans-XYZ:3000/original/url`.

* there will be a parameter to define the probability of relaying the call to another node (DT). The default value will be 0.5 and 0 will disable it.

      OPBEANS_DT_PROBABILITY=0.5

**Note**: some opbeans implementations have non-standard endpoints in the `/api/` namespace. These shouldn't be affected by the randomized forwarding

Implemented in:

 * [x] `compose.py` (https://github.com/elastic/apm-integration-testing/pull/197)
 * [x] opbeans-node (https://github.com/elastic/opbeans-node/pull/40)
 * [x] opbeans-ruby (https://github.com/elastic/opbeans-ruby/pull/8)
 * [x] opbeans-java (https://github.com/elastic/opbeans-java/pull/14)
 * [x] opbeans-go (https://github.com/elastic/opbeans-go/pull/10)
 * [x] opbeans-python (https://github.com/elastic/opbeans-python/pull/18)

**Comment by mikker** [comment]
For good measure: What are the _standard_ endpoints in `/api`?

**Comment by watson** [comment]
For reference, here's how we have split up `/api/*` into its own service for opbeans-node: https://github.com/elastic/opbeans-node/pull/36

**Comment by alvarolobato** [comment]
What percentage should be used when flipping a coin? 50%?

**Comment by watson** [comment]
The opbeans-node agent have the following HTTP endpoints:

- `GET /is-it-coffee-time` - Not called by the UI and probably unique to opbeans-node
- `GET /log-error` - Not called by the UI and probably unique to opbeans-node
- `GET /log-message` - Not called by the UI and probably unique to opbeans-node
- `GET /throw-error` - Not called by the UI and probably unique to opbeans-node
- `GET /throw-async-error` - Not called by the UI and probably unique to opbeans-node
- `GET /api/stats`
- `GET /api/products`
- `GET /api/products/top`
- `GET /api/products/:id`
- `GET /api/products/:id/customers`
- `GET /api/types`
- `GET /api/types/:id`
- `GET /api/customers`
- `POST /api/customers` - This one is special to opbeans-node and isn't used by the UI yet
- `GET /api/customers/:id`
- `GET /api/orders`
- `POST /api/orders` - This one isn't used by the UI, but by the workload script
- `GET /api/orders/:id`
- `GET /*` - Catch all that doesn't match any of the above. Used to service static files to the frontend

**Comment by beniwohli** [comment]
> 
> 
> For reference, here's how we have split up `/api/*` into its own service for opbeans-node: [elastic/opbeans-node#36](https://github.com/elastic/opbeans-node/pull/36)

To be frank, I'd prefer if you reverted that once we have this thing going. It'll be confusing why transactions/traces from opbeans-node look slightly different than everybody else

**Comment by watson** [comment]
@beniwohli On the other hand, this removes the issue of recursion. If all opbeans-* exposed two services like this, the other opbeans-* could just call that one to not trigger the random proxy again. That way we'd not have an infinite loop of proxy calls 😅

But I'm not sure how easy it is for other languages to how multiple services in the same container like we do for opbeans-node

**Comment by alvarolobato** [comment]
For this first iteration I would keep it simple, the odds of a very long trace are very low.

**Comment by alvarolobato** [comment]
@elastic/apm-agent-devs thanks for doing this in record time. Closing the issue
