### ISSUE TITLE
Option to not starting opbeans load generator

### ISSUE THREAD

**Issue by watson** [elastic/apm-integration-testing#213]
If you start any of the opbeans images, the load generator will start as well. It would be nice if there was an option to run opbeans without the load generator

**Comment by watson** [comment]
The main reason why this would be nice, is that it adds about 1 minute to the boot up time to spin up the load generator on my mac even if I don't need it 😅

**Comment by kuisathaverat** [comment]
related to https://github.com/elastic/apm-integration-testing/issues/173

**Comment by kuisathaverat** [comment]
resolved in https://github.com/elastic/apm-integration-testing/pull/648
