### ISSUE TITLE
implement --opbeans-java-agent-branch/repo

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#218]
They don't do anything currently and cause:

```
[Warning] One or more build-args [JAVA_AGENT_BRANCH JAVA_AGENT_REPO] were not consumed
```

like elastic/apm-integration-testing#208

**Comment by graphaelli** [comment]
Just in the case where those are set right?  That seems reasonable enough.

**Comment by kuisathaverat** [comment]
I think is resolved
