### ISSUE TITLE
add secret token to apm-server endpoint configuration

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#221]
success means running `tests/server/test_transaction.py` against an apm-server with a secret token set.

**Comment by kuisathaverat** [comment]
related to https://github.com/elastic/apm-integration-testing/issues/13

**Comment by kuisathaverat** [comment]
I think is fully covered on https://github.com/elastic/apm-integration-testing/pull/737
WDYT? @graphaelli

**Comment by graphaelli** [comment]
agreed, thanks!
