### ISSUE TITLE
[APM-CI][Integration test] Unify version/package/branch/whatever parameters names for compose.py and scripts

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#226]
We are modifying the composer.py to support using a version from a commit SHA, reviewing the configuration of agents and opbeans modules, we saw that there are no common criteria to name the parameters (go-agent-version, nodejs-agent-package, rum-agent-branch, ...) IMHO should be only one way, I mean, you want to set the version/package/branch/whatever to use, if we have 3 different ways to set it you have to remember 3 different parameters. I will open a discussion about it. 

WDYT?

@elastic/apm-server @elastic/apm-agent-devs

**Comment by watson** [comment]
Sorry, I am unfamiliar with the problem you're solving. Could you explain a little more about which config options you would like to change the values for?

**Comment by beniwohli** [comment]
I did something similar a few weeks ago for the opbeans services: https://github.com/elastic/apm-integration-testing/pull/198 (although I didn't add flags for `--opbeans-XYZ-agent-version` yet)

**Comment by kuisathaverat** [comment]
Those are the options that we have to select application versions, you can see that there are not common criteria, we will need to support branch/tag/commit/release version selection for many (probably all) of them, so we need to review all and choose a common way to set the version to grab/compile. 

```
  --java-agent-version JAVA_AGENT_VERSION
  --nodejs-agent-package NODEJS_AGENT_PACKAGE
  --python-agent-package PYTHON_AGENT_PACKAGE
  --rum-agent-branch RUM_AGENT_BRANCH
  --ruby-agent-version RUBY_AGENT_VERSION
  --ruby-agent-version-state RUBY_AGENT_VERSION_STATE
  --apm-server-version APM_SERVER_VERSION
  --elasticsearch-version ELASTICSEARCH_VERSION
  --filebeat-version FILEBEAT_VERSION
  --kibana-version KIBANA_VERSION
  --logstash-version LOGSTASH_VERSION
  --metricbeat-version METRICBEAT_VERSION
  --opbeans-go-agent-branch OPBEANS_GO_AGENT_BRANCH
  --opbeans-java-agent-branch OPBEANS_JAVA_AGENT_BRANCH
  --opbeans-node-agent-branch OPBEANS_NODE_AGENT_BRANCH
  --opbeans-python-agent-branch OPBEANS_PYTHON_AGENT_BRANCH
  --opbeans-ruby-agent-branch OPBEANS_RUBY_AGENT_BRANCH
```

This is also related to these three current PRs
https://github.com/elastic/apm-integration-testing/pull/225
https://github.com/elastic/apm-integration-testing/pull/223
https://github.com/elastic/apm-integration-testing/pull/222

**Comment by watson** [comment]
My 5 cents: Under normal operation, using the agent version is the most user-friendly IMO. But sometimes it's nice to be able to specify either a git branch/commit/etc or a path to a local folder when testing an unreleased feature

**Comment by graphaelli** [comment]
I think you can skip this support for non-APM components:
```
  --elasticsearch-version ELASTICSEARCH_VERSION
  --filebeat-version FILEBEAT_VERSION
  --kibana-version KIBANA_VERSION
  --logstash-version LOGSTASH_VERSION
  --metricbeat-version METRICBEAT_VERSION
```

Are you proposing we merge `--apm-server-version` with `--apm-server-build` ?

**Comment by axw** [comment]
I always get dizzy with the number of flags to compose.py. How about this?

- change `--with-apm-server` so that it accepts an optional string value. So `--with-apm-server` would store True, omitting the flag would store the default, and any value specified would be stored as a string (`--with-apm-server=foo` with store `"foo"`). String values would accommodate either a stack version number, or a github URL with branch/commit
- collapse flags like `--opbeans-ruby-agent-branch` and `--ruby-agent-version` into just `--ruby-agent`, and treat like above: accept either a version (language-specific) which would be pulled from rubygems/pypi/npm/whatever, or a github URL. Don't support having different agent versions for the opbeans service and other dockerized test services.

**Comment by kuisathaverat** [comment]
I like it, this will reduce the number of compose flags to half or less ;)

>String values would accommodate either a stack version number, or a github URL with branch/commit

ok, for branch and tags it is easy to use a ref (refs/heads/BRANCH_NAME or refs/tags/NAME), for commits there is not ref AFAIK, but it is easy to differentiate a SHA1 from a ref so easy to implement too.

e.g.

* `--with-apm-server` it uses default version (master)
* `--with-apm-server=refs/heads/6.x`it used the branch `6.x`
* `--with-apm-server=refs/tags/v6.4`it used the tag `v6.4`
* `--with-apm-server=d0c7cb1859ed70bf314b48963ed36a0a6b3141ac`it used the commit `d0c7cb1859ed70bf314b48963ed36a0a6b3141ac`

* `--ruby-agent` it uses default version (master)
* `--ruby-agent=refs/heads/1.x`it used the branch `1.x`
* `--ruby-agent=refs/tags/v1.0.0`it used the tag `v1.0.0`
* `--ruby-agent=d0c7cb1859ed70bf314b48963ed36a0a6b3141ac`it used the commit `d0c7cb1859ed70bf314b48963ed36a0a6b3141ac`
* `--ruby-agent=@1.0.0`it used the released version `1.0.0` from the package repository (rubygems/pypi/npm/whatever).

**Comment by watson** [comment]
I like this approach, however if I may suggest a slight style change [borrowed from the npm world](https://docs.npmjs.com/files/package.json#dependencies) as this has proven a very logical and easy way of doing it:

- In `package.json` you can specify a dependency as just by the version, e.g. `1.2.3` - which will make it fetch the officially released version from the registry

- You can also specify it as a url [pointing to a tar ball](https://docs.npmjs.com/files/package.json#urls-as-dependencies), e.g. `http://example.com/foo.tar.gz`. This might not be that usable for us, but I included it here for completeness. But I'm ok with not supporting this

- But what is really nice is that you also can specify [any valid git url](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies): `git://github.com/watson/apm-agent-nodejs.git#v1.2.3`

- There's also [a shorthand](https://docs.npmjs.com/files/package.json#github-urls) for specifying git url's if the repo is hosted on github: `watson/apm-agent-nodejs#v1.2.3` or `watson/apm-agent-nodejs`

- Finally you can specify [local paths](https://docs.npmjs.com/files/package.json#local-paths), which I would really like, but I'm not sure that's easy for us to do, so maybe that can't be supported: `file:../foo/bar`

With this style, you haven't locked down which repo to fetch the agent from. This allows us to use PR branches on our own personal forks which is really useful for testing things before they are merged.

**Comment by beniwohli** [comment]
Just keep in mind that all of this has to be implemented in platform specific ways in the entrypoint scripts (and for Go and possibly Java, in the Dockerfile), What I like about the current 3 flags is that it is quite easy to write up the logic in bash. I wouldn't want to do all of the options y'all propose in bash, but that may just be bash-hating me.

**Comment by kuisathaverat** [comment]
>You can also specify it as a url pointing to a tar ball, e.g. http://example.com/foo.tar.gz. This might not be that usable for us, but I included it here for completeness. But I'm ok with not supporting this

We can use it to download releases from Github

e.g. https://github.com/elastic/apm-server/archive/v6.4.3.tar.gz

>But what is really nice is that you also can specify any valid git url: git://github.com/watson/apm-agent-nodejs.git#v1.2.3
>There's also a shorthand for specifying git url's if the repo is hosted on github: watson/apm-agent-nodejs#v1.2.3 or watson/apm-agent-nodejs
>Finally you can specify local paths, which I would really like, but I'm not sure that's easy for us to do, so maybe that can't be supported: file:../foo/bar

They are documented and allow you to checkout other repo different than the main repo, in the other hand, you need to know the organization, repository of the code, and are longer to write, they could be a 'nice to have'

> I wouldn't want to do all of the options y'all propose in bash, but that may just be bash-hating me.

😃 sure, the hard part should be in the compose.py on the Docker files we can use `[` to check an environment variable and execute the proper download/checkout/whatever 

e.g.

[ -n "${XXXX_RELEASE}" ] && ...
[ -n "${XXXX_COMMIT}" ] && ...
[ -n "${XXXX_BRANCH}" ] && ...
