### ISSUE TITLE
support release differences more sustainably

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#261]
This repo currently runs the same tests against all versions of the Elastic Stack.  This requires compatibility code this about to get more challenging to maintain, as the next major release makes significant changes to the field names of APM data.

Proposal: Continue launching supported versions of the Elastic Stack using `compose.py` but split integration tests to support major versions.  

To accomplish this, maintain a branch per supported major.  `compose.py` on `master` can still launch all versions of the stack but the `6.x` branch would maintain tests that are only compatible with that major, `master` would test against `7.x` (then the same transition would happen around `8.x`).  This means the version matrices will be split by major.  Probably a good thing since exclusions starting to dominate now anyway.

**Comment by graphaelli** [comment]
@kuisathaverat Are you available to pick this up?  I can grab it if not, it's rather urgent as tests against 6.x stacks will fail until we address this.

**Comment by kuisathaverat** [comment]
@graphaelli I will pick it up Tomorrow in my morning, I will make a new branch in the apm-integration-testing compatible with APM version 6.x, so the master would be 7.x compatible until we have 8.x, then I will make a job for this 6.x similar to https://apm-ci.elastic.co/job/elastic+apm-integration-testing+master+periodic/, I suppose that this is the urgent part. finally, we will try to build both stack test in the same way (job) and be prepared for the next stack version.

I will cut the branch in the last successful build https://apm-ci.elastic.co/job/elastic+apm-integration-testing+master+multijob-testsuite/71/testReport/

**Comment by graphaelli** [comment]
That's great news, thank you @kuisathaverat!  I actually branched a `6.x` before merging #263 but feel free to branch elsewhere and force push if needed, though I don't that will be necessary.

**Comment by kuisathaverat** [comment]
I am testing the first version https://github.com/elastic/apm-integration-testing/pull/265, it mostly works, I have to review some tests that are falling before started, and I have to generate an HTML file from the JSON result file. On a second iteration, we can tray to split test on different jobs and put some code in the library for reutilization.

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-integration-tests-mbp/detail/PR-265/4/pipeline/23
https://apm-ci.elastic.co/job/apm-server/job/apm-integration-tests-mbp/job/PR-265/4/artifact/results.json

![image](https://user-images.githubusercontent.com/5400788/50986970-8d890680-1508-11e9-95c2-613e83c1f36e.png)

**Comment by kuisathaverat** [comment]
Now report also an HTML table results

https://apm-ci.elastic.co/job/apm-server/job/apm-integration-tests-mbp/job/PR-265/13/artifact/results.html

![image](https://user-images.githubusercontent.com/5400788/51048976-cee2ea00-15cc-11e9-91d1-c855d6d8fd3d.png)

**Comment by kuisathaverat** [comment]
I am closing the Axis test reusable way for Python and other Agents, as soon as I finished we can review the new PR that will supersede #265

**Comment by kuisathaverat** [comment]
Main Build
![image](https://user-images.githubusercontent.com/5400788/51258303-f6113100-19a9-11e9-8eda-b6ea688967a3.png)

Downstream build per Agent
![image](https://user-images.githubusercontent.com/5400788/51258324-02958980-19aa-11e9-9aa5-debd64eafb1f.png)

Artifacts
![image](https://user-images.githubusercontent.com/5400788/51258423-3c669000-19aa-11e9-83b9-a6d246d5e5dc.png)

Results.json
![image](https://user-images.githubusercontent.com/5400788/51258398-2c4eb080-19aa-11e9-8155-f38b6128d720.png)

Result.html
![image](https://user-images.githubusercontent.com/5400788/51258443-50aa8d00-19aa-11e9-930f-3ac96e770d88.png)
