### ISSUE TITLE
Test Installation of APM Server on different platforms

### ISSUE THREAD

**Issue by simitt** [elastic/apm-integration-testing#27]
Figure out where to put those tests:
- https://github.com/elastic/beats-tester
- directly into apm-integration-testing: either request a windows slave for jenkins or use vagrant or ignore windows and mac for now and only automate linux based installations
- https://github.com/elastic/elastic-stack-testing

**Comment by kuisathaverat** [comment]
superseded by https://github.com/elastic/apm-server/issues/2733
