### ISSUE TITLE
Investigate broken tests for 6.2, 6.3, 6.4 stack

### ISSUE THREAD

**Issue by simitt** [elastic/apm-integration-testing#288]
With https://github.com/elastic/apm-integration-testing/pull/287 testing the stack from 6.2 - 6.4 has been disabled, as those tests were broken and showed red for all tests, which leads to ignoring test failures. 
This should be fixed and enabled again asap.

**Comment by graphaelli** [comment]
v1 tests for 6.x resolved addition of `6.x-v1` branch + #330
