### ISSUE TITLE
ignore docker-summary errors

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#295]
`docker-summary.sh` triggers this:

```
Error response from daemon: configured logging driver does not support reading
```

and exit immediately.  Those containers should just be ignored.

**Comment by kuisathaverat** [comment]
https://github.com/elastic/apm-integration-testing/pull/379
https://github.com/elastic/apm-integration-testing/pull/378
https://github.com/elastic/apm-integration-testing/pull/377
