### ISSUE TITLE
decommission apm-ci

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#308]
In favor of continuous-integration/jenkins/pr-merge.

Opening to continue discussion started in https://github.com/elastic/apm-integration-testing/pull/303#issuecomment-460496061

**Comment by kuisathaverat** [comment]
The webhook has deleted, so the old jobs would not be trigger anymore.

**Comment by graphaelli** [comment]
lgtm

**Comment by kuisathaverat** [comment]
https://github.com/elastic/infra/pull/9927
