### ISSUE TITLE
restart rum agent gracefully when timeout occurs

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-integration-testing#360]
Currently when the page timeouts with default timeout https://github.com/prisma-archive/chromeless/blob/master/docs/api.md#api-goto), the rum tasks print outs the error and dies. 
```js
Error: wait(page load event) timed out after 10000ms
    at Timeout._onTimeout (/home/chrome/node_modules/chromeless/dist/src/util.js:180:32)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

```

We would need to fix it with a graceful restart of crawling the page.

**Comment by graphaelli** [comment]
Does the container go unhealthy or terminate at that point?  We could set a [restart](https://docs.docker.com/compose/compose-file/#restart) policy for this container if it would help.

**Comment by kuisathaverat** [comment]
I have added a health check option a few days ago 
https://github.com/elastic/apm-integration-testing/pull/386
https://github.com/elastic/apm-integration-testing/pull/393
https://github.com/elastic/apm-integration-testing/pull/394
