### ISSUE TITLE
Add `service.environment` for opbeans services

### ISSUE THREAD

**Issue by formgeist** [elastic/apm-integration-testing#442]
I would like to add the following `service.environment` variables to the opbeans services.

- **opbeans-java**
  - production
  - dev-1
  - qa-test
- **opbeans-go**
  - production
  - dev
- **opbeans-ruby**
  - production
  - development

**Comment by graphaelli** [comment]
A single environment per service should be straightforward, any thoughts on how to handle multiple?

**Comment by formgeist** [comment]
@graphaelli Perhaps this is more of a task for the automation team to handle in their dev setup for Observability. I imagine the best results will come from spinning up multiple agents handling each environment, so the relations between say `dev` traces are kept in sync. Thoughts?

**Comment by graphaelli** [comment]
I agree that would be a better fit.

**Comment by formgeist** [comment]
Closing as I've opened https://github.com/elastic/observability-dev/issues/62
