### ISSUE TITLE
[apm-integration-testing] Respect newly added users.

### ISSUE THREAD

**Issue by simitt** [elastic/apm-integration-testing#454]
Currently new users can be added in a running instance via Kibana, but the users are not valid for usage afterwards. 

How to reproduce:
* start ES and Kibana instance, e.g. `./scripts/compose.py start master --xpack-secure`
* go to Kibana management page and add user
* log out and try to login with the user or try to use the user as ES user in the output for an APM Server instance.

**Comment by bmorelli25** [comment]
Not sure if it obvious, but the _Create or update roles API_ and _Create or update users API_ also don't work for me. They return `"created" : true`, you just can't use the users afterwards.

**Comment by kuisathaverat** [comment]
weird, I not sure if it could be related to how we launch Elasticsearch, I do not think so, but we'll take a look.

**Comment by graphaelli** [comment]
> start ES and Kibana instance, e.g. `./scripts/compose.py start master`

WIth `--xpack-secure` right?

**Comment by simitt** [comment]
Right @graphaelli , I updated the entry.
