### ISSUE TITLE
Integration Testing - Add basic support for frontend js agent

### ISSUE THREAD

**Issue by simitt** [elastic/apm-integration-testing#46]

**Comment by formgeist** [comment]
@simitt is this an issue to simply add JS agent support (along with opbeans-react) to the integration testing setup? cc @jahtalab

**Comment by formgeist** [comment]
It's added now https://github.com/elastic/apm-integration-testing/pull/110#event-1699542711 or does this issue include testing as well?

**Comment by jahtalab** [comment]
I have created this [issue](https://github.com/elastic/apm-agent-js-base/issues/10) to keep track of this task, so far we run the tests in Travis against apm-server Docker image. I am planning to use the same tests in the integration testing.
