### ISSUE TITLE
Run `--no-kibana` without `heartbeat`

### ISSUE THREAD

**Issue by formgeist** [elastic/apm-integration-testing#474]
I very often run Kibana locally for testing purposes, while running everything else through Docker. I'm used to be able to start up everything _but_ Kibana using;

`scripts/compose.py start master --all --no-kibana` but now I'm getting the following error;

`ERROR: Service 'heartbeat' depends on service 'kibana' which is undefined.`

Trying to add `--no-heartbeat` doesn't help the situation. Anyway to remedy this?

**Comment by kuisathaverat** [comment]
the `--all` and the `--no-XXX` option enter on conflict, the alternative would be to enable what you want that it is not all. The following command will run all opbeans,  elasticsearch, APM Server, opbeans-loadgenerator, and auxiliar docker containers (databases)

```
scripts/compose.py start master --all-opbeans --no-kibana
```

**Comment by kuisathaverat** [comment]
but, I found an error on the configuration of the heartbeat docker container it deletes the enable_kibana option I dunno why.

**Comment by kuisathaverat** [comment]
PR https://github.com/elastic/apm-integration-testing/pull/476

**Comment by formgeist** [comment]
thanks @kuisathaverat 🎉
