### ISSUE TITLE
[automation][integration-testing] All test is broken

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#496]
After merge https://github.com/elastic/apm-integration-testing/pull/494 there are three tests broken 

test_conc_req_all_agents – tests.agent.test_multiple_agents
test_concurrent_req_dotnet_foobar – tests.agent.test_dotnet
test_concurrent_req_dotnet – tests.agent.test_dotnet

```
> frame.get(attr) for frame in stacktrace), stacktrace[0].keys()
E AssertionError: dict_keys(['exclude_from_grouping', 'filename', 'line', 'function', 'module'])
```

**Comment by SergeyKleyman** [comment]
@kuisathaverat Could you please clarify which branch caused this to happen: 

```
> frame.get(attr) for frame in stacktrace), stacktrace[0].keys()
E AssertionError: dict_keys(['exclude_from_grouping', 'filename', 'line', 'function', 'module'])
```

After I removed some asserts in #494 I cannot find any references to `'function'` ot `'module'` on master.

**Comment by kuisathaverat** [comment]
We are reviewing it we detected the fail in a PR, the master seems ok, I've relaunched the build because it should be resolved.
