### ISSUE TITLE
[Automation] Create a new 7.x branch

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#512]
We're starting working on the next major version 8.x, this means that we need to create a new branch for 7.x and bump the Elastic Stack version on the master to 8.x

**Comment by v1v** [comment]
7.x branch is now up and running:
- https://github.com/elastic/apm-integration-testing/tree/7.x

I created the below commit:
- https://github.com/elastic/apm-integration-testing/commit/7a379065f1de02178afa4ae4fc851717a7cea710

Not sure whether the upgrade scripts should be also changed. @graphaelli and @kuisathaverat what do you think?

Regarding the 8.x version, I'll raise a PR with the suggested changes.

**Comment by kuisathaverat** [comment]
I think 8.0.0 is correct
