### ISSUE TITLE
Add pre-commit stage

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#548]
we've configured pre-commit in the repository so we can add a pre-commit stage to make the same checks 

related PR https://github.com/elastic/apm-integration-testing/pull/547

**Comment by v1v** [comment]
For the record https://github.com/elastic/apm-pipeline-library/pull/128 might help regarding the yamllint and shellcheck dependencies

**Comment by v1v** [comment]
PR: https://github.com/elastic/apm-integration-testing/pull/555
