### ISSUE TITLE
APM Agent configuration doesn't work with --xpack-secure

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-integration-testing#573]
APM Agent configuration doesn't seem to work when using `--xpack-secure`. Tested on both `master` and `7.3`

The page just shows "Loading". The console shows:
```log
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:5601/api/apm/settings/agent-configuration
```
<img width="831" alt="Screen Shot 2019-08-14 at 3 16 12 PM" src="https://user-images.githubusercontent.com/5618806/63060227-7e0adb00-bea6-11e9-8f2b-48aeaa4be4aa.png">

Everything works as expected when `--xpack-secure` is omitted.

This is related to https://github.com/elastic/kibana/issues/43326. In this case though, it doesn't even work with the right privileges.

**Comment by kuisathaverat** [comment]
it is an issue in the APM UI, there is not too much to do on the integration test to avoid it, I think we can close it. @bmorelli25 WDYT?

**Comment by bmorelli25** [comment]
Yup, thanks Ivan. Looks like this was fixed in https://github.com/elastic/kibana/pull/44970.
