### ISSUE TITLE
[ECK] Run and automate tests on ECK infrastructure

### ISSUE THREAD

**Issue by simitt** [elastic/apm-integration-testing#575]
Set up integration testing to be able to run with ECK infrastructure (ES, Kibana, APM Server). Automate to run tests on ECK on a regular schedule. 

cc @pebrc @elastic/apm-server @elastic/observablt-robots

**Comment by kuisathaverat** [comment]
[Elastic Cloud on Kubernetes (ECK)](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html) I think this should be included on the observability-test-environments continuous deployment roadmap because it is a test against a different infrastructure.

**Comment by alvarolobato** [comment]
@kuisathaverat will talk with the cloud team and understand the current situation of ECK so we can decide what approach we will follow here. This seems like a different deployment to what we have on our clusters and many need a big rearchitechture.

**Comment by kuisathaverat** [comment]
I've checked the documentation and also talk with Sebastian from Cloud Team, ECK is only the new k8s operators, for now, there is a discussion about adding some other services we have in Elastic Cloud but for now, it is only the k8s operators. So we can test the APM Server deploy with ECK easily changing our k8s deployment for the ECK k8s operator.

**Comment by kuisathaverat** [comment]
How to test snapshot on ECK https://github.com/elastic/seceng/issues/687

**Comment by simitt** [comment]
Was this closed intentionally or is it a zubebot bug?

**Comment by kuisathaverat** [comment]
I have moved it to the wrong column
