### ISSUE TITLE
apm-server + logstash + ILM

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#580]
When using logstash to index apm-server output while ILM is enabled, this change is needed:

```patch
diff --git a/docker/logstash/pipeline/apm.conf b/docker/logstash/pipeline/apm.conf
index 1db7fdc..31fc1df 100644
--- a/docker/logstash/pipeline/apm.conf
+++ b/docker/logstash/pipeline/apm.conf
@@ -34,6 +34,6 @@ filter {
 output {
   elasticsearch {
     hosts => ["elasticsearch:9200"]
-    index => "%{[@metadata][beat]}-%{[@metadata][version]}%{[@metadata][index_suffix]}-%{+YYYY.MM.dd}"
+    index => "%{[@metadata][beat]}-%{[@metadata][version]}%{[@metadata][index_suffix]}"
   }
 }
```

it would also be nice to include `pipeline => "apm"` for versions that install that pipeline.

**Comment by kuisathaverat** [comment]
ILM is enabled by default on APM Server 7.3, so we can apply the changon on master and 7.x branches

**Comment by kuisathaverat** [comment]
Do you mean something like this command?

`./scripts/compose.py start 7.1.0 --apm-server-snapshot --with-logstash`

this will use the `./docker/logstash/pipeline-6.x-compat/:/usr/share/logstash/pipeline/` that it is not correct for the APM Server 8.0.0-SNAPSHOT, I'll try to figure out how to make it works.

**Comment by kuisathaverat** [comment]
done, now the following commands will use the correct pipeline for the APM Server version

`./scripts/compose.py start 7.1.0 --apm-server-version=7.3.0 --with-logstash`
`./scripts/compose.py start 7.1.0 --apm-server-snapshot --with-logstash`
