### ISSUE TITLE
--python-agent-package not working

### ISSUE THREAD

**Issue by basepi** [elastic/apm-integration-testing#603]
Here is the command I was testing with:

```
./scripts/compose.py start master --with-agent-python-django --with-opbeans-python --with-filebeat --python-agent-package=git+https://github.com/elastic/apm-agent-python.git@master --force-build
```

I realized that it wasn't actually installing from the apm-agent-python master branch. After looking around more (and inspecting `--help`), I tried this:

```
./scripts/compose.py start master --with-agent-python-django --with-opbeans-python --with-filebeat --python-agent-package='github;master' --force-build
```

Still no dice, as verified by putting `echo` statements into [the entrypoint.sh](https://github.com/elastic/apm-integration-testing/blob/master/docker/opbeans/python/entrypoint.sh). It was just installing the upstream package. In fact, none of the env variables were even populated.

Am I doing something wrong? As far as I can tell, both of my commands above are valid ways to evoke `compose.py`.

**Comment by basepi** [comment]
I ended up doing my testing by editing [entrypoint.sh](https://github.com/elastic/apm-integration-testing/blob/master/docker/opbeans/python/entrypoint.sh) and manually inserting the correct install source location. But I lost a fair amount of time before I realized what was happening -- or, more precisely what wasn't happening. :)

**Comment by beniwohli** [comment]
I think the confusion here is between `--with-agent-python-django` (a very small test app for integration testing) and `--with-opbeans-python` (the opbeans app). `--python-agent-package` only applies to the former, for the latter you need to use `--opbeans-python-agent-repo` and `--opbeans-python-agent-branch`.

That *is* super confusing and needs to be documented better, at least.

**Comment by kuisathaverat** [comment]
I guess you want to run the Opbeans-python with the Python agent from the master branch, to do that you have to use the `--opbeans-python-*` parameters not `--python-agent-*`

`./scripts/compose.py start master --with-opbeans-python --with-filebeat --opbeans-python-agent-branch=master --force-build`

**Comment by basepi** [comment]
Ah, thank you for the clarifications. I'll probably try to add some documentation around this once I'm finished with my testing.
