### ISSUE TITLE
Fix the timeout issue with the opbeans RUM load generator

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-integration-testing#611]
Currently if the page load takes longer than 10000 it throws an error and exists the process:

```
Error: wait(page load event) timed out after 10000ms
    at Timeout._onTimeout (/home/chrome/node_modules/chromeless/dist/src/util.js:180:32)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

We should either increase the timeout or catch and handle this error properly!

**Comment by jahtalab** [comment]
@kuisathaverat , is it possible to prioritise this? It is causing the demo data to be inconsistent.

**Comment by v1v** [comment]
@sqren , where have you seen this particular issue? what are the steps required to reproduce it?

Thanks
