### ISSUE TITLE
Replace chromeless with puppeteer in the opbeans RUM load generator

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-integration-testing#612]
[Puppeteer](https://github.com/GoogleChrome/puppeteer) is the official chrome controller from google chrome team.

**Comment by kuisathaverat** [comment]
we are testing [Cypress](https://www.cypress.io/) that integrates perfectly with [cucumber](https://cucumber.io/)  here there is an example https://github.com/elastic/observability-test-environments/tree/master/tests/functional-opbeans

**Comment by beniwohli** [comment]
@kuisathaverat I'm not sure if the two things are related. `opbeans-rum` is more of a load generator than a testing tool.

I think it's important to move away from Chromeless ASAP, as it is the cause of all remaining open security issues in this repo. I'll give it a quick try and open a PR if it is successful.

**Comment by jahtalab** [comment]
Addressed via #691, thanks @beniwohli for the PR!
