### ISSUE TITLE
Ensure `service.version` changes from time to time

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-integration-testing#688]
In https://github.com/elastic/kibana/pull/52640, we are displaying markers in the charts for when versions are "first seen", meaning the timestamp for the first event that has a distinct value for `service.version` per `service.name`. The opbeans apps are currently all reporting either no value for `service.version`, or the same one for all recorded events. This makes testing out of the box a little difficult because data needs to be augmented. 

Preferably the apm-integration-testing environment generates events with versions that change over time, so we see multiple versions for a given service.

**Comment by beniwohli** [comment]
maybe we could set it to the agent version, now that most (or all?) opbeans variants get automatically built when a new version of the agent is released? Not sure how useful it would be though, as release frequency isn't that high.

**Comment by kuisathaverat** [comment]
yep, this is the best option once we would have the Opbeans release process in place in every Opbean, as a workaround we can make that one of the Opbeans generate a random `service.version` on each build, this means that every time you launch the `compose.py` with the option `--force-build` this service name would change, Would it be enough for the moment @dgieselaar ?

**Comment by dgieselaar** [comment]
I think it is. @sqren when apm.elstc.co is redeployed, do we pass the `--force-build` flag?

**Comment by kuisathaverat** [comment]
checking how to implement it I have found that there is a flaw to change the service name for every opbeans, so it is implemented you only have to add a parameter like this one `--opbeans-go-service-name "opbeans-go-$RANDOM"` it would generate an environment variable like `ELASTIC_APM_SERVICE_NAME=opbeans-go-8391`

```
  --opbeans-dotnet-service-name OPBEANS_DOTNET_SERVICE_NAME
  --opbeans-dotnet01-service-name OPBEANS_DOTNET01_SERVICE_NAME
  --opbeans-go-service-name OPBEANS_GO_SERVICE_NAME
  --opbeans-go01-service-name OPBEANS_GO01_SERVICE_NAME
  --opbeans-java-service-name OPBEANS_JAVA_SERVICE_NAME
  --opbeans-java01-service-name OPBEANS_JAVA01_SERVICE_NAME
  --opbeans-python-service-name OPBEANS_PYTHON_SERVICE_NAME
  --opbeans-python01-service-name OPBEANS_PYTHON01_SERVICE_NAME
  --opbeans-ruby-service-name OPBEANS_RUBY_SERVICE_NAME
  --opbeans-ruby01-service-name OPBEANS_RUBY01_SERVICE_NAME
```

**Comment by sqren** [comment]
@dgieselaar 
> when apm.elstc.co is redeployed, do we pass the --force-build flag?

Currently, no. But would be very easy to add.

**Comment by formgeist** [comment]
@kuisathaverat Was there a PR for this that got merged? Not seeing any reference in the issue ^

**Comment by kuisathaverat** [comment]
It is a really old PR https://github.com/elastic/apm-integration-testing/pull/120

**Comment by beniwohli** [comment]
@kuisathaverat I think there's a misunderstanding. This issue is about introducing variation in the service *version*, not service *name*. Those are two different settings and end up in different fields in the intake API and Elasticsearch.

**Comment by kuisathaverat** [comment]
this PR changes the static `"ELASTIC_APM_SERVICE_NAME=opbeans-XXXX` to `"ELASTIC_APM_SERVICE_NAME={}".format(self.service_name),` and introduces the parameter 

```
        if hasattr(cls, 'DEFAULT_SERVICE_NAME'):
            parser.add_argument(
                '--' + cls.name() + '-service-name',
                default=cls.DEFAULT_SERVICE_NAME,
                dest=cls.option_name() + '_service_name',
                help="service name"
            )
```

no sure if it is the final implementation of the setting, but in any case, it does not matter the setting is there and it was implemented at some point.

**Comment by dgieselaar** [comment]
@kuisathaverat I'm not sure if I follow - as Benjamin said, the issue is about different values for `service.version`, but the fragment that you posted is about `service.name`. How is it related?

**Comment by kuisathaverat** [comment]
🤦‍♂ I was reading `service.version` as `service.name` for some reason and does not matter how many times I've read it, I read it always wrong, this kind of thins that happened in my mind 😫, sorry for my stupidity

**Comment by dgieselaar** [comment]
@kuisathaverat any chance of getting this in before 7.6 freezes? Would help with our testing plan etc.

**Comment by kuisathaverat** [comment]
@cachedout this is a good one to start with integration tests, it is about to add a new parameter to `compose.py` to set the `service.version` on the agents, basically, we have to add a new parameter for the opbeansservice and an environment variable (ELASTIC_APM_SERVICE_VERSION) to each opbeans, then we have to add a new test to check the existence of the env var when the parameter is set, finally, we probably have to fix some tests 😄 

https://github.com/elastic/apm-integration-testing/blob/master/scripts/modules/opbeans.py#L17-L18
https://github.com/elastic/apm-integration-testing/blob/master/scripts/modules/opbeans.py#L70
https://github.com/elastic/apm-integration-testing/blob/master/scripts/modules/opbeans.py#L123
https://github.com/elastic/apm-integration-testing/blob/master/scripts/tests/service_tests.py#L224-L225

**Comment by cachedout** [comment]
@kuisathaverat I have now merged https://github.com/elastic/apm-integration-testing/pull/709. Could you help me understanding what else remains in order to close this issue?

**Comment by kuisathaverat** [comment]
@cachedout you can close it

**Comment by dgieselaar** [comment]
@kuisathaverat @cachedout does this also mean that running apm-it will mean that we get events with changing versions?

**Comment by kuisathaverat** [comment]
@dgieselaar to change the service version you have to pass a parameter like the following `--opbeans-java-service-version 1.2.3`
