### ISSUE TITLE
set apm-server mode to experimental by default

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-integration-testing#753]
+ Since we already know apm-server mode `experimental` feature works out of the box and helps immensely while developing new features and also for the space time projects. it makes total sense to set the mode by default for all supported versions. https://github.com/elastic/apm-server/pull/1961

**Comment by kuisathaverat** [comment]
To use something experimental as default sounds a little heavy, keep in mind that it would affect our integration test. Add a flag to enable it sounds reasonable.

**Comment by kuisathaverat** [comment]
the new flag ``will add the parameter `-E apm-server.mode=experimental` to the APM Server command line, this option is available since APM Server 7.2

**Comment by simitt** [comment]
This would not influence the CI test runs. It is not an experimental feature in the sense of adding some early stage feature, but rather enables developers to add new fields that get dynamically indexed for developing POCs for new features.
I don't have a strong opinion about enabling by default or only providing a flag, but don't see any harm in enabling by default.
