### ISSUE TITLE
add `--elasticsearch-enable-tls` and `--kibana-enable-tls` new flag to enable TLS

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#810]
It is not possible to run Elasticsearch and Kibana with TLS enabled, adding these two flags  `--elasticsearch-enable-tls` and `--kibana-enable-tls` we can test both with TLS enabled by default, it should be pretty similar to `--apm-server-enable-tls` and we can use the same certificate

**Comment by v1v** [comment]
See [notes](https://www.elastic.co/blog/configuring-ssl-tls-and-https-to-secure-elasticsearch-kibana-beats-and-logstash?ultron=june-2019&blade=newsletter&hulk=email&mkt_tok=eyJpIjoiTlRBM1pqWTJPV0ppWldaaiIsInQiOiJiXC96b2JuZ0pUWEpCUDNzWDNlcmZualRmejM0blBVTk5tWFRsbTVubk9FXC9PNVIzTkIweWRGdXBzdXdmTjhPV0dyOFNPSzRuT3NZVXcwMDd6SFdnUFUxVnhoa29iWHZnRUJRbzd2Y1wveXE1MXUrVzlkdG96dnFcL1dabjNTczlUaXoifQ%253D%253D#step-2-4) to setting up the TLS for testing alerts here?
