### ISSUE TITLE
opbeans-rum image won't build

### ISSUE THREAD

**Issue by smith** [elastic/apm-integration-testing#824]
Getting this error when it's running `apt-get update -qq`:

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: GPG error: http://security.debian.org/debian-security stretch/updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian stretch-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian stretch-updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian stretch Release: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian stretch Release' is not signed.
```

**Comment by v1v** [comment]
I cannot reproduce the above error:
- https://gist.github.com/v1v/8526b357ac1f5b9cc0efdf6ed494953c

Where did you see it? Off the top of my head, could it be related to the debian mirrors themselves? Maybe the mirror in a particular region was somehow compromised?

**Comment by smith** [comment]
@v1v I think you might have the image for `node:12-slim` cached. What happens if you:

```
docker ps -a | grep node:12-slim | cut -d ' ' -f 1 | xargs docker rm
```

to delete any local, already-built copies of `node:12-slim` and then run it again?

**Comment by smith** [comment]
Apparently the Docker VM's disk was full. Running `docker images prune` cleared up enough to where it's working now. 

Looking at  https://stackoverflow.com/questions/59139453/repository-is-not-signed-in-docker-build solved it for me.
