### ISSUE TITLE
Add default parameter when running Kibana to opt-out from Telemetry

### ISSUE THREAD

**Issue by afharo** [elastic/apm-integration-testing#829]
We can see many telemetry reports in our Telemetry Production cluster from instances that are created and stopped on the same day and with the name `cluster_name: "docker-cluster"`. 

Can we add the option `--telemetry.optIn=false` in the Kibana service's start command to opt-out from sending any telemetry reports?

**Comment by kuisathaverat** [comment]
Let's disable telemetry by default, and add a flag to enable it when we need it.

**Comment by kuisathaverat** [comment]
Let's disable telemetry by default, and add a flag to enable it when we need it.

**Comment by kuisathaverat** [comment]
I've checked it, we set the env var `XPACK_XPACK_MAIN_TELEMETRY_ENABLED`, but it has changed on https://github.com/elastic/kibana/commit/c308048f04e245080fa51e1be2cdc12668c33740 so I've tried to set a similar env var for the new setting, I didn't have too much luck, none of the following env vars disable the telemetry 😞 @afharo Do you know if there is an env var to disable telemetry?

```
        "xpack.telemetry.enabled": "false",
        "xpack_telemetry_enabled": "false",
        "xpackTelemetryEnabled": "false",
        "telemetryEnabled": "false",
        "telemetry.enabled": "false",
        "telemetry_enabled": "false",
        "XPACK_TELEMETRY_ENABLED": "false",
```

**Comment by afharo** [comment]
I can see that env var comes from [here](https://github.com/elastic/kibana-docker/blob/master/.tedi/template/kibana-docker#L147). But that repo is archived and used only for releases pre-6.6 (according to its readme).

I tried to find the new version of it in the Kibana repo: https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/resources/bin/kibana-docker#L237

I guess you are looking for either `TELEMETRY_ENABLED` or `TELEMETRY_OPTIN` 😉

**Comment by afharo** [comment]
Note that this only works for docker builds (which I believe it's your case anyway) 😃
