### ISSUE TITLE
Integration test fails on every PR to JS agent

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-integration-testing#844]
+ Integration tests for JS agent seems to be not working for last couple of days. Happens to be an issue with Pupetter and playwright trying to install chromium and getting failed. 

```
puppeteer@1.20.0 install /app/elastic-apm-rum/node_modules/puppeteer

 node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

Error: read ECONNRESET

    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)

  -- ASYNC --

    at BrowserFetcher.<anonymous> (/app/elastic-apm-rum/node_modules/puppeteer/lib/helper.js:111:15)

    at Object.<anonymous> (/app/elastic-apm-rum/node_modules/puppeteer/install.js:64:16)

    at Module._compile (internal/modules/cjs/loader.js:1133:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

    at Module.load (internal/modules/cjs/loader.js:977:32)

    at Function.Module._load (internal/modules/cjs/loader.js:877:14)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)

    at internal/main/run_main_module.js:18:47 {

  errno: 'ECONNRESET',

  code: 'ECONNRESET',

  syscall: 'read'

```

Test run - https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-tests-selector-mbp/detail/master/8637/pipeline

**Comment by v1v** [comment]
I think that's an issue with the upstream (the opbeans-frontend). I'm running:
- [build](https://apm-ci.elastic.co/job/apm-agent-rum/job/opbeans-frontend-mbp/job/master/34/)

And also locally:

```
cd opbeans-frontend
make build
```

But I cannot reproduce it using the master branch.

## Question

- https://github.com/elastic/apm-agent-rum-js/pull/796 could be the reason for the above error?

- Could the opbeans-frontend skip the puppet download by default when building the agent from source code?

**Comment by vigneshshanmugam** [comment]
> elastic/apm-agent-rum-js#796 could be the reason for the above error?

Nope, it fails on all PR's.  

>Could the opbeans-frontend skip the puppet download by default when building the agent from source code?

I am not sure though, seems to be an issue with playwright and puppeteer on the same repo.

**Comment by kuisathaverat** [comment]
it is flaky, it fails to download the chrome package randomly, indeed I relaunch that build and success https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-tests-selector-mbp/detail/master/8648/pipeline so the only thing we can do is retry the whole thing.

>Could the opbeans-frontend skip the puppet download by default when building the agent from source code?

I think the can add the variable `ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=%{PUPPETEER_SKIP_CHROMIUM_DOWNLOAD}` to the Dockerfile of the opbean and pass the argument to the build to disable the Chrome install on those builds we do not go to test anything.

**Comment by vigneshshanmugam** [comment]
There are some workarounds to change the network host that happens due to the network issue -  https://github.com/puppeteer/puppeteer/issues/1597
