### ISSUE TITLE
Error while loading shared libraries: libXss.so.1

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#870]
Today we start to show the following error on RUM test

```
AssertionError: Expected done, got Failed to launch chrome! /rumjs-integration-test/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory   TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

**Comment by v1v** [comment]
I also saw it and somehow I was expecting it could be flaky but it looks suspicious since it happens for 7.x and master branches :/

@vigneshshanmugam  and @jahtalab any hints?

Build logs:
- https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-integration-test-downstream/branches/master/runs/5895/nodes/77/steps/98/log/?start=0

You can reproduce it locally with

```
# Let's clone the repo
git clone git@github.com:elastic/apm-integration-testing.git .apm-its
cd .apm-its
git checkout 698b948e4fd4c3d219328d112aafac472af1ec92

# Let's run the apm-integration testing for rum
export ELASTIC_STACK_VERSION=8.0.0
export BUILD_OPTS= 
APM_SERVER_BRANCH_VERSION=master
.ci/scripts/rum.sh

make stop-env || echo 'Failed to stop the environment'
```

**Comment by kuisathaverat** [comment]
it affects to the APM server too https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2Fmaster/detail/master/530/tests

 cc @elastic/apm-server

**Comment by vigneshshanmugam** [comment]
@kuisathaverat @v1v I did some dry runs and adding `libxss` deps to the RUM docker fixes the issue. But i am still not sure why that happened out of sudden today, I dont know the root cause, but it seems to be a good workaround for now #872 

```
tests/agent/test_rum.py::test_rum PASSED
```

**Comment by kuisathaverat** [comment]
yes that the solution I tested it

**Comment by DanRoscigno** [comment]
@vigneshshanmugam , I pulled master and am still not getting libxss installed.  I am seeing the error still and I exec'd in and used apt list to see if it was there but it is not.

**Comment by kuisathaverat** [comment]
The CI  is installing the libxss1 package and the test pass

https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-integration-test-downstream/branches/master/runs/5905/nodes/77/log/?start=0

```
[2020-07-09T10:41:42.891Z] Step 5/18 : RUN apt update -qq     && apt install -qq -y curl git gnupg libgconf-2-4 libxss1 --no-install-recommends     && curl -sSfkL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'     && apt update -qq     && apt install -qq -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont python g++ build-essential       --no-install-recommends     && rm -rf /var/lib/apt/lists/*     && rm -rf /src/*.deb
[2020-07-09T10:41:42.891Z]  ---> Running in 7420e44de957
[2020-07-09T10:41:43.842Z] 
...
[2020-07-09T10:41:56.443Z] Selecting previously unselected package libxss1:amd64.
[2020-07-09T10:41:56.443Z] Preparing to unpack .../40-libxss1_1%3a1.2.2-1_amd64.deb ...
[2020-07-09T10:41:56.443Z] Unpacking libxss1:amd64 (1:1.2.2-1) ...
...
[2020-07-09T10:41:59.866Z] Setting up libxss1:amd64 (1:1.2.2-1) ...
```

locally it also install the library and pass the tests

```
# Let's clone the repo
git clone git@github.com:elastic/apm-integration-testing.git .apm-its
cd .apm-its
git checkout 698b948e4fd4c3d219328d112aafac472af1ec92

# Let's run the apm-integration testing for rum
export ELASTIC_STACK_VERSION=8.0.0
export BUILD_OPTS= 
APM_SERVER_BRANCH_VERSION=master
.ci/scripts/rum.sh

make stop-env || echo 'Failed to stop the environment'
```

@DanRoscigno I am not sure what could happen on your environment but the issue we have on our Integration test is resolved.
