### ISSUE TITLE
Remove v1 Intake Tests

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#887]
The 4 agents supporting the original v1 intake have reached EOL, meaning we can drop v1 from the testing matrix now.

**Comment by kuisathaverat** [comment]
so we can delete the 6.x-v1 branch 👍

**Comment by kuisathaverat** [comment]
@gil on the master branch I found a couple of `v1` related code, the source maps load and the test upgrade, Do we want to delete them too?

https://github.com/elastic/apm-integration-testing/blob/master/scripts/modules/cli.py#L656-L718
https://github.com/elastic/apm-integration-testing/blob/master/tests/server/test_upgrade.py

**Comment by graphaelli** [comment]
Wow, I had forgotten about that sourcemap upload utility - I guess we haven't updated it since the move to `/assets/v1/sourcemaps`.  I think it's ok to remove and count on adding it later if needed.  The upgrade test can go in its current form.

**Comment by cachedout** [comment]
I'm not too familiar with the backstory on this one but it looks like there used to be a dedicated branch for these tests and it's been removed? I don't see `test_upgrade.py` anymore either.

So, I'm going to guess that this is probably ready to be closed. @kuisathaverat or @graphaelli any objections?

**Comment by kuisathaverat** [comment]
yeah, I think it is resolved a long time ago.
