### ISSUE TITLE
--kibana-enable-tls doesn't work

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-integration-testing#920]
~~I think that changing only /scripts/modules/cli.py#L396 is not enough; as still can't navigate eg. to `app/management/ingest/beats_management`~~

Update: eventually found that the issue for a feature not working was that it requires running Kibana with TLS enabled, but the Kibana container stops when passing `--kibana-enable-tls`. Kibana logs are filled with `"No living connections"` messages.

**Comment by kuisathaverat** [comment]
it is trying to connect to Elasticsearch by https 

```
{"type":"log","@timestamp":"2020-09-24T08:09:00Z","tags":["warning","elasticsearch","data"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2020-09-24T08:09:03Z","tags":["warning","elasticsearch","data"],"pid":7,"message":"Unable to revive connection: https://elasticsearch:9200/"}
```

the workaround is to enable TLS for Elasticsearch too

`./scripts/compose.py start 7.9 --release --kibana-enable-tls --elasticsearch-enable-tls`

**Comment by jalvz** [comment]
thanks!
