### ISSUE TITLE
Different environment variables in Jenkins vs locally

### ISSUE THREAD

**Issue by basepi** [elastic/apm-integration-testing#963]
Recently, I was debugging an issue, which resulted in https://github.com/elastic/apm-integration-testing/pull/962.

One reason it took a long time for me to figure out the root cause was that I couldn't reproduce the issue locally.

It turns out the environment variables present in Jenkins are different than those in my local integration test runs.

Here are the commands I ran locally:

```
./scripts/compose.py start 8.0.0 --with-agent-python-flask --no-kibana --no-xpack-secure --with-agent-python-django --python-agent-package git+https://github.com/basepi/apm-agent-python.git@293518bfa0bae4ed02e824265bed7021d061233d --opbeans-python-agent-branch 293518bfa0bae4ed02e824265bed7021d061233d
make docker-test-agent-python
```

The environment variable in question is `ELASTIC_APM_LOG_LEVEL`. As of #962 that particular method of reproducing this issue probably won't work since I removed all references for Python. But I think it would be worth investigating why this mismatch occurred in the first place.

**Comment by kuisathaverat** [comment]
all the builds have a docs.txt file in artifacts with the exact commands the CI run. These commands are the correct ones to replicate the issues from the CI.

https://apm-ci.elastic.co/job/apm-integration-tests-selector-mbp/job/master/11429/artifact/docs.txt

```
Let's generate the details to help to reproduce it locally ...


# Let's clone the repo
git clone git@github.com:elastic/apm-integration-testing.git .apm-its
cd .apm-its
git checkout 61095d6867b593e2240c84dbca57cb62f899d6b7

# Let's run the apm-integration testing for python
export ELASTIC_STACK_VERSION=8.0.0
export BUILD_OPTS="--with-agent-python-flask --python-agent-package git+https://github.com/basepi/apm-agent-python.git@9aabf4051def17293857e389369e69d9aca260e2 --opbeans-python-agent-branch 9aabf4051def17293857e389369e69d9aca260e2"
.ci/scripts/agent.sh python python-django
.ci/scripts/opbeans-app.sh python python-django python

make stop-env || echo 'Failed to stop the environment'

ls -ltrh
```

Also, the build in the CI has a dump of the data in Elasticsearch after the test `tests/results/data-TEST_NAME-error.json`
<img width="1233" alt="Screenshot 2020-11-07 at 01 05 19" src="https://user-images.githubusercontent.com/5400788/98425431-526ca580-2095-11eb-8bac-60b3058f7ded.png">

for more details https://github.com/elastic/observability-dev/blob/master/docs/apm/apm-integration-test-troubleshooting-guide.md

**Comment by basepi** [comment]
Yes, I'm realizing I made some false assumptions about those scripts -- I assumed they would be running the tests locally, but didn't open them to take the time to investigate there.

I do get failures when I run the commands above, specifically:

```
[ERROR] Failed waiting for all containers are healthy
make[1]: *** [dockerized-test] Error 1
make: *** [docker-test-agent-python] Error 2
```

But maybe next week I will pull the scripts apart and see if I can solve those errors to reproduce the error locally. (For science!)

**Comment by basepi** [comment]
Thanks again for answering all my questions over the last couple of days, @kuisathaverat! I've learned a lot and shouldn't get stumped as easily next time.

**Comment by kuisathaverat** [comment]
I have open this one https://github.com/elastic/apm-integration-testing/issues/964 about the error with docker-compose-wait
