### ISSUE TITLE
docker-compose-wait does not work if you do not have a clean docker images history clean

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#964]
docker-compose-wait check the docker images ran in your system and check is all are healthy, this work well when you Docker history (docker ps -a) only have healthy Docker images, but does not work if you have unhealthy Docker images in the history, when this happens the command failed.

```
[ERROR] Failed waiting for all containers are healthy
make[1]: *** [dockerized-test] Error 1
make: *** [docker-test-agent-python] Error 2
```

We have to find a more proper wait to wait for all Docker images ready, I think that a proper solution is to add a docker container that depends on all docker container then this container will wait until all are running.

**Comment by v1v** [comment]
> We have to find a more proper wait to wait for all Docker images ready, I think that a proper solution is to add a docker container that depends on all docker container then this container will wait until all are running.

+100, we use something similar in the opbeans, see https://github.com/elastic/opbeans-java/blob/0ac733323620c2d2d3a0325b2b4fa1bb17601a8d/docker-compose.yml#L117-L121
