### ISSUE TITLE
[APM-CI][Integration test] add nice status summary

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-integration-testing#98]
like we used to have

**Comment by kuisathaverat** [comment]
Right now  we have different level of detail about status oin the integration test

* Branch level: it show the status by APM Server compatibility version
<img width="1259" alt="Screenshot 2019-03-22 at 14 09 12" src="https://user-images.githubusercontent.com/5400788/54824806-46f41d00-4cac-11e9-91d0-5c815660119e.png">

* Agent level: on each build we see the status of each agent
<img width="1160" alt="Screenshot 2019-03-22 at 14 09 28" src="https://user-images.githubusercontent.com/5400788/54824807-478cb380-4cac-11e9-9d34-1cddbeb2b420.png">

* Agent version: on each downstream build we have the details about agent versions with ussues
<img width="1588" alt="Screenshot 2019-03-22 at 14 09 45" src="https://user-images.githubusercontent.com/5400788/54824809-478cb380-4cac-11e9-98cb-1b0198f2d1a0.png">

Those result are also available in a HTML file and JSON file
<img width="849" alt="Screenshot 2019-03-22 at 14 10 13" src="https://user-images.githubusercontent.com/5400788/54824810-48254a00-4cac-11e9-9961-322b879dc5e8.png">

Ithink the only part is not cover it is to have a dashboard in some Elasticsearch with the global results uploaded, so we only have to upload the result.json file to someplace

**Comment by kuisathaverat** [comment]
related to https://github.com/elastic/apm-dev/issues/536
